# Generated by Django 5.2.10 on 2026-01-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
