# Generated by Django 5.2.10 on 2026-01-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='atendido_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
