# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_atendido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo_dano',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='procedimiento',
            field=models.TextField(blank=True, default=''),
        ),
    ]
